In [1]:
# Load package 
import numpy as np

<h1> Exercise 1: The Simplest Consumption Model (Cake Eating Problem)

Consider the simplest consumption-saving model:

$$\begin{align*}
    V_1^*(W) &= \max_{c_1,c_2,\dots,c_T} \{ \sqrt{c_1} +\beta \sqrt{c_2}+\beta^2\sqrt{c_3}+\cdots+\beta^T\sqrt{c_T} \} \\
    & \text{s.t.} \\
    W &= c_1 + c_2+\cdots+c_T \\
    c_t &\in \mathbb{N}, \, \forall t
\end{align*}$$
for $T=3$, $\beta =0.9$ and $W=5$.

### 1. Solve the model using backwards induction: 

In [2]:
# 1. Setup 
beta = 0.9
W = 5
T = 3

# 2. Initialize
Vstar_bi = np.nan+np.zeros([W+1,T]) #Make a (W+1)xT matrix of NaNs
Cstar_bi = np.nan + np.zeros([W+1,T]) #Make a (W+1)xT matrix of NaNs
Cstar_bi[:,T-1] = np.arange(W+1) #Set the last period to be the whole cake
Vstar_bi[:,T-1] = np.sqrt(Cstar_bi[:,T-1]) #Compute the value of the last period

In [ ]:
# 3. solve
# Loop over periods backwards
for t in range(T-2, -1, -1):  #from period T-2, until period 0, backwards  
    
    #loop over states
    for w in range(W+1):
        c = np.arange(w+1)
        w_c = w - c
        V_next = Vstar_bi[w_c,t+1]
        V_guess = np.sqrt(c)+beta*V_next #(w+1) vector of possible values next period
        Vstar_bi[w,t] = np.amax(V_guess) #Find the maximum value
        Cstar_bi[w,t] = np.argmax(V_guess) #Find the corresponding consumption (in this case equal to the index of the maximum value)
        
print(Cstar_bi)

IndexError: index 8 is out of bounds for axis 1 with size 3

### 2. Fill in Exercise_1.py with a function with $\beta$, $W$ and $T$ as inputs

### 3. Import the function and check that it works 

Notice, C is our policy function. The policy function tells us the optimal way of spending our resources in a given period. 

In [4]:
from Exercise_1 import solve_backwards

beta = 0.9
W = 5
T = 3
C,V = solve_backwards(beta=beta, W=W, T=T)
print(C)
print(V)

[[0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 2.]
 [1. 2. 3.]
 [2. 2. 4.]
 [2. 3. 5.]]
[[0.         0.         0.        ]
 [1.         1.         1.        ]
 [1.9        1.9        1.41421356]
 [2.71       2.31421356 1.73205081]
 [3.12421356 2.68700577 2.        ]
 [3.49700577 3.00484301 2.23606798]]


### 4. Use the policy function to simulate how 5 resources now can be spend optimally over 3 periods.    

In [5]:
# 4. simulate
C_backwards = np.empty(T) #Make an empty vector of length T to store optimal consumption in
W_now = W #Set the initial cake size to W

for t in range(T): #Loop forwards over periods
    W_now = int(W_now)   # change the type to integreger 0,1,2,3 and so on
    C_backwards[t] = C[W_now, t]
    W_now = W_now - C_backwards[t]
    
print(C_backwards)

[2. 2. 1.]


### 5. Solve the model for $T = 10$.

In [23]:
# 1. Setup 
beta = 0.9
W = 5
T = 10

# 2. - 3. Solve 
C10, V10 = solve_backwards(beta,W,T)  # call function

Simulate $C_1$, $C_2$,...,$C_{10}$ using the policy function found in 5) and W=5

In [24]:
# Define function to simulate
def simulate(Cstar,T,W):
    C_backwards = np.empty(T)
    W_now = W
    for t in range(T):
        W_now = int(W_now)   # change the type to integreger 0,1,2,3 and so on
        C_backwards[t] = Cstar[W_now, t]
        W_now = W_now - C_backwards[t]
        
    return C_backwards


# 4. Simulate
C_sim = simulate(C10,T,W)  # Call function
        
print('Solution for C with T =',T,'and W =', W , ': C =',C_sim)

Solution for C with T = 10 and W = 5 : C = [1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]


Play around with W, $\beta$ and see the results. Are the results inline with your intuition?